### ISSUE TITLE
Basic readme example not cleaning up stuff?

### ISSUE THREAD

**Issue by alessioalex** [AmpersandJS/ampersand-router#39]
```js
    home: function () {
        this.trigger('newPage', new HomePage());
    },
```

This means that whenever you go to the homepage it will create a new instance of `HomePage` and probably bind some events. That code suggests that the events don't get cleaned up.

I think it's better to update the example to either store the last view and then cleanup or to use the [ampersand-view-switcher](https://github.com/ampersandjs/ampersand-view-switcher).

**Comment by lukekarrys** [comment]
I think incorporating `ampersand-view-switcher` into the readme example is a little outside the scope of the router's documentation, since it would also require us to show the code for a view to instantiate the view-switcher.

I do think the example should be updated. I'm thinking we should put a note in there, about using `app.trigger` like we do in the ampersand cli generated app's [router](https://github.com/AmpersandJS/ampersand/blob/41ff011c43e4d3adab06b4b1941583034d58195f/template/shared/client/router.js#L24-L26) and [main view](https://github.com/AmpersandJS/ampersand/blob/41ff011c43e4d3adab06b4b1941583034d58195f/template/shared/client/views/main.js#L19).

I'll work on getting a PR with the updated example.
